spring:
  profiles:
    active : dev
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  sql:
    init:
      platform: postgres
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
---